name: Maven Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven tests
      - name: Run Maven tests
        run: mvn test

      # Step 5: Print test result summary
      - name: Print test result summary
        run: |
          if [ -f target/surefire-reports/TEST-*.xml ]; then
            echo "### Test Results Summary" >> $GITHUB_STEP_SUMMARY
            grep -E "<testsuite" target/surefire-reports/TEST-*.xml | \
              sed -E 's/.*name="([^"]+)".*tests="([^"]+)".*failures="([^"]+)".*errors="([^"]+)".*/- Test Suite: \1\n  - Tests: \2\n  - Failures: \3\n  - Errors: \4/' >> $GITHUB_STEP_SUMMARY
          else
            echo "No test results found." >> $GITHUB_STEP_SUMMARY
          fi
