name: Maven Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven tests and capture summary
      - name: Run Maven tests
        run: |
          mvn test | tee maven-test-output.log
          echo "### Test Results Summary" >> $GITHUB_STEP_SUMMARY
          grep -A 10 "\[INFO\] Results:" maven-test-output.log >> $GITHUB_STEP_SUMMARY

      # Debug Step: Print Maven test output log
      - name: Print Maven test output log
        run: cat maven-test-output.log
